# Datos de contenido para los 5 nichos
import random

PRODUCTIVIDAD = [
    {"kw":"como organizar tu dia con chatgpt","target":"organizar tu dia con ChatGPT","title":"Como organizar tu dia con ChatGPT en 5 minutos","desc":"Aprende a usar ChatGPT para planificar tu dia de forma optima. Prioriza tareas, gestiona tu tiempo y se mas productivo desde ya.","sections":[("Planifica tu dia en segundos","El mejor momento para planificar tu dia con ChatGPT es por la manana, antes de empezar a trabajar. Usa este prompt: 'Eres un planificador experto. Hoy tengo estas tareas: [lista]. Dispongo de [X] horas. Dame un plan horario optimizado, priorizando por importancia y urgencia. Incluye bloques de enfoque de 90 minutos y pausas de 10.' Este prompt te da un plan realista que cumples, no uno imposible."),("Gestiona interrupciones con IA","Las interrupciones son el mayor enemigo de la productividad. ChatGPT puede ayudarte a gestionarlas: 'Acabo de recibir una tarea urgente [descripcion]. Mi plan actual es [plan]. Como reajusto mi dia sin sacrificar lo importante? Dame 3 opciones.' La IA te da alternativas que un humano tardaria 15 minutos en pensar."),("Prompt experto para planificacion semanal","El prompt definitivo: 'Eres mi asistente de productividad personal. Analiza mi calendario de la semana y mis objetivos. Identifica: 1) Los 3 momentos de mayor enfoque, 2) Posibles conflictos de tiempo, 3) Tareas que puedo delegar o eliminar. Dame un plan optimo.' Este ahorra 30 minutos cada lunes.")]},
    {"kw":"gestionar tiempo con inteligencia artificial","target":"gestionar tiempo con IA","title":"Gestiona tu tiempo con inteligencia artificial como un CEO","desc":"Tecnicas de gestion del tiempo potenciadas con IA. Multiplica tu productividad sin trabajar mas horas.","sections":[("Auditoria de tiempo con ChatGPT","Primero necesitas saber donde se va tu tiempo. Prompt: 'He registrado mi tiempo esta semana: [datos]. Analiza como lo he invertido y dime: 1) Porcentaje de tiempo en tareas importantes vs urgentes, 2) Patrones de procrastinacion, 3) Las 2 cosas que podria eliminar para ganar 5 horas semanales.'"),("Time blocking con prompts","El time blocking es la tecnica mas efectiva. Prompt: 'Dame un time blocking schedule para manana. Tengo [horas] disponibles. Mis prioridades son: [lista]. Quiero 3 bloques de enfoque profundo de 90 minutos separados por tareas administrativas.'"),("Elimina ladrones de tiempo","Prompt: 'Describo mi dia tipico: [detalle]. Identifica mis 5 mayores ladrones de tiempo. Para cada uno, dame una estrategia concreta para eliminarlo o reducirlo en un 50%.'")]},
    {"kw":"escribir emails mas rapido con chatgpt","target":"escribir emails mas rapido con ChatGPT","title":"Escribe emails profesionales en 1 minuto con ChatGPT","desc":"Redacta emails perfectos en segundos con prompts de IA. Ahorra horas cada semana en tu bandeja de entrada.","sections":[("El prompt para emails profesionales","El prompt basico que uso a diario: 'Eres mi asistente de comunicacion. Necesito un email sobre [asunto]. Tono: [profesional/cercano]. Destinatario: [cliente/jefe]. Accion requerida: [que necesito]. Dame 3 versiones.' Ahorra 10-15 minutos por email importante."),("Bandeja de entrada cero con IA","Prompt: 'Tengo 50 emails sin leer. Clasificalos en: responder hoy, responder esta semana, delegar, archivar. Para los de responder hoy, dame un borrador de 2 lineas.' En 5 minutos tienes la bandeja vacia."),("Emails dificiles con ChatGPT","Prompt: 'Necesito escribir un email para rechazar una propuesta sin quemar puentes. El contexto es: [situacion]. Dame 3 enfoques: directo, diplomatico y constructivo.'")]},
    {"kw":"automatizar tareas repetitivas con ia","target":"automatizar tareas repetitivas con IA","title":"Automatiza tus tareas repetitivas con inteligencia artificial","desc":"Delega tareas tediosas a la IA y recupera horas cada semana. Automatizacion con prompts de ChatGPT.","sections":[("Identifica que automatizar","Prompt: 'Describo mi trabajo diario: [lista de tareas]. Identifica cuales se pueden automatizar con IA, cuales delegar, y cuales requieren mi atencion. Para las automatizables, dame el prompt exacto.'"),("Automatiza resumenes y analisis","Una de las tareas mas automatizables: 'Eres mi asistente de analisis. Te paso [documento/reunion/articulo]. Extrae: puntos clave, decisiones, acciones pendientes, preguntas sin responder.' Ahorra 20 minutos por documento."),("Crea plantillas reutilizables","Crea tu biblioteca personal de prompts para tareas recurrentes. Una hora invirtiendo en crear estas plantillas te ahorra 5 horas cada semana.")]},
    {"kw":"tomar notas reuniones con chatgpt","target":"tomar notas de reuniones con ChatGPT","title":"Toma notas de reuniones perfectas con ChatGPT","desc":"Deja de tomar notas manualmente. Usa ChatGPT para resumir reuniones, extraer acciones y compartir minutas.","sections":[("Minutas perfectas","Despues de cada reunion: 'Eres un secretario ejecutivo. A partir de estas notas genera: 1) Resumen ejecutivo, 2) Decisiones tomadas, 3) Acciones pendientes, 4) Proximos pasos. Formato profesional.'"),("Reuniones con clientes","'Genera un email de seguimiento para el cliente. Incluye: agradecimiento, resumen de lo acordado, proximos pasos con fechas. El cliente debe sentirse valorado.'"),("Acciones inteligentes post-reunion","Prompt avanzado: 'Ademas del resumen, identifica: 1) Tareas que puedo delegar, 2) Riesgos no mencionados, 3) Siguiente reunion: temas a tratar.'")]},
    {"kw":"crear sistema productividad con chatgpt","target":"crear un sistema de productividad con ChatGPT","title":"Crea tu sistema de productividad personal con ChatGPT","desc":"Construye un sistema de productividad a medida con IA. Organizacion, seguimiento y mejora continua automatizados.","sections":[("Disena tu sistema","Prompt: 'Ayudame a disenar un sistema de productividad personal. Trabajo [horas/dia] en [sector]. Mis problemas: [lista]. Necesito: planificacion diaria, seguimiento semanal y revision mensual.'"),("Implementa el sistema","'Crea una plantilla para mi revision semanal: logros, pendientes, ajustes, leccion aprendida. Quiero completarla en 10 minutos.'"),("Mejora continua","Cada semana: 'Esta es mi revision: [datos]. Que patrones ves? Dame 3 cambios concretos para la proxima semana.'")]},
    {"kw":"priorizar tareas con inteligencia artificial","target":"priorizar tareas con IA","title":"Prioriza tus tareas como un experto con IA","desc":"Usa ChatGPT para matrices de priorizacion, gestion de proyectos y toma de decisiones.","sections":[("Matriz Eisenhower con IA","'Aplica la matriz de Eisenhower a estas tareas: [lista]. Clasifica: urgente+importante, importante+no urgente, urgente+no importante, ni urgente ni importante.'"),("Priorizacion valor vs esfuerzo","'Tengo estos proyectos con impacto y esfuerzo: [datos]. Prioriza usando matriz valor-esfuerzo. Dame el top 5 ordenado por mejor relacion.'"),("Decisiones complejas","'Ayudame a decidir entre [A] y [B]. Criterios: [lista]. Dame analisis multicriterio con recomendacion.'")]},
    {"kw":"organizar proyectos con chatgpt","target":"organizar proyectos con ChatGPT","title":"Organiza y gestiona proyectos con ChatGPT","desc":"Planifica, ejecuta y da seguimiento a tus proyectos usando IA. Gestion de proyectos sin complicaciones.","sections":[("Planifica el proyecto","'Ayudame a planificar: [proyecto]. Objetivo: [meta]. Fecha tope: [fecha]. Dame: WBS, hitos, dependencias, riesgos y mitigaciones.'"),("Seguimiento semanal","'Actualizo mi proyecto: [avance]. Voy segun lo planeado? Identifica desviaciones, tareas criticas y recursos necesarios.'"),("Comunicacion del proyecto","'Crea un informe de avance para [stakeholders]. Incluye: % completado, hitos, proximos pasos, riesgos. Tono profesional.'")]},
    {"kw":"mejorar enfoque trabajo con ia","target":"mejorar el enfoque en el trabajo con IA","title":"Mejora tu enfoque con inteligencia artificial","desc":"Tecnicas de productividad profunda potenciadas con IA. Elimina distracciones y concentrate mejor.","sections":[("Preparate para el enfoque","Prompt: 'Voy a tener una sesion de enfoque de 90 minutos sobre [tema]. Dame 3 objetivos concretos, los recursos necesarios y como manejare interrupciones.'"),("Gestiona distracciones","'Acabo de perder 30 minutos en [distraccion]. Analiza por que ocurrio y dame 3 estrategias para evitarlo.'"),("Entorno de trabajo optimo","'Describo mi entorno: [descripcion]. Dame recomendaciones para optimizarlo: iluminacion, ruido, digital y fisico.'")]},
    {"kw":"resumir documentos con chatgpt","target":"resumir documentos con ChatGPT","title":"Resume documentos largos con ChatGPT","desc":"Ahorra horas de lectura usando ChatGPT para resumir informes, libros y documentos extensos.","sections":[("Resumenes ejecutivos","'Resume este documento en: resumen ejecutivo (3 lineas), puntos clave (5), datos relevantes, conclusiones.'"),("Resumenes por niveles","'Dame 3 versiones: 1) Para el CEO (2 lineas), 2) Para mi equipo (1 parrafo), 3) Para mi (detallado).'"),("Extrae aprendizajes","'Extrae de este articulo: 1) Las 3 ideas principales, 2) Ejemplos concretos, 3) Datos relevantes, 4) Como aplicarlo esta semana.'")]},
    {"kw":"planificar semana con chatgpt","target":"planificar la semana con ChatGPT","title":"Planifica tu semana en 10 minutos con ChatGPT","desc":"Deja de perder los lunes planificando. Usa ChatGPT para una semana organizada y productiva.","sections":[("La revision del domingo","'Mis objetivos esta semana: [lista]. Mis reuniones: [calendario]. Pendientes: [lista]. Dame plan diario priorizado, bloques de enfoque y los 3 resultados clave.'"),("Ajustes a mitad de semana","'Mi plan era [plan]. Lo que paso: [realidad]. Como reajusto para cumplir objetivos? Prioriza.'"),("La retrospectiva del viernes","'Mi semana en datos: [logros, fracasos]. Dame retrospectiva: que funciono, que no, 3 cambios para la proxima.'")]},
    {"kw":"delegar tareas con ia","target":"delegar tareas a la IA","title":"Aprende a delegar tareas a la inteligencia artificial","desc":"Delegar no es solo pedir. Aprende a dar instrucciones precisas a ChatGPT para resultados profesionales.","sections":[("El arte del prompt para delegar","'Necesito que hagas [tarea]. Contexto: [que, para que, formato]. Si necesitas mas informacion, preguntame antes de continuar.'"),("Revisa lo que devuelve","'Revisa lo que acabas de generar. Hay errores? Seniala cualquier cosa incorrecta para un experto.'"),("Crea un sistema de delegacion","'Ayudame a crear un sistema: checklist de que delegar, plantillas de prompts, proceso de revision.'")]},
    {"kw":"productividad personal con gemini","target":"productividad personal con Gemini","title":"Guia de productividad personal con Google Gemini","desc":"Usa Google Gemini para organizar tu vida personal y profesional. Prompts para el asistente de Google.","sections":[("Gemini integrado con Google","'Conecta con mi calendario. Analiza mi semana: tiempo real para trabajo profundo, reuniones que podria acortar, bloques optimos.'"),("Gestion de proyectos con Gemini","'Usa Google Drive para analizar documentos de mi proyecto: estado, hitos, docs desactualizados, decisiones pendientes.'"),("Flujo Gemini + herramientas","'Eres mi asistente central. Integra calendario, emails, Drive. Dame briefing diario: que paso ayer, que toca hoy, que estoy olvidando.'")]},
    {"kw":"organizar tareas diarias con claude","target":"organizar tareas diarias con Claude","title":"Organiza tus tareas diarias con Claude AI","desc":"Usa Claude AI para gestionar tu lista de tareas. Prompts optimizados para Claude.","sections":[("Contexto largo de Claude","Claude procesa documentos enormes: 'He pegado mi historico de 3 meses. Analiza patrones de tareas incompletas, eficiencia, y recomendaciones.'"),("Organizacion diaria","'Basado en notas de ayer, pendientes y calendario, genera plan de accion priorizado por deadlines, dependencias y mi energia.'"),("Claude como coach","'Actua como mi coach. He tenido un dia [bueno/malo]. Analiza por que y dame feedback y 1 ajuste para manana.'")]},
    {"kw":"automatizar informes semanales con ia","target":"automatizar informes semanales con IA","title":"Automatiza tus informes semanales con IA","desc":"Deja de perder horas en informes. ChatGPT genera reportes profesionales con solo darle los datos.","sections":[("Estructura del informe","'Genera informe: resumen ejecutivo, KPIs, logros, incidencias, plan proxima semana. Tono profesional.'"),("Datos crudos a informe","'Te paso datos de la semana: [datos]. Analiza tendencias y genera informe ejecutivo. Destaca lo bueno, malo y sorprendente.'"),("Para diferentes audiencias","'Genera 3 versiones: para mi jefe (metricas), equipo (detalles), stakeholders (vision general).'")]},
]

FINANZAS = [
    {"kw":"controlar gastos mensuales con chatgpt","target":"controlar gastos mensuales con ChatGPT","title":"Controla tus gastos mensuales con ChatGPT","desc":"Usa IA para analizar, categorizar y optimizar tus gastos. Ahorra dinero sin esfuerzo.","sections":[("Categoriza gastos","'Clasifica estos gastos en: vivienda, alimentacion, transporte, ocio, suscripciones. Dame total por categoria y % sobre el total. Identifica gastos innecesarios.'"),("Presupuesto inteligente","'Crea un presupuesto mensual realista basado en mis ingresos [X] y gastos [datos 3 meses]. Incluye ahorro objetivo del 20%. Senala donde gasto de mas.'"),("Alertas de gasto","'Cada semana te paso gastos. Alerta si estoy gastando mas del presupuesto en alguna categoria.'")]},
    {"kw":"planificar ahorro con ia","target":"planificar el ahorro con IA","title":"Planifica tu ahorro mensual con inteligencia artificial","desc":"Estrategias de ahorro personalizadas con IA. Ahorra mas sin sacrificar calidad de vida.","sections":[("Diagnostico financiero","'Analiza mi situacion: ingresos [X], gastos [Y], deudas [Z]. Estoy en buena salud financiera? Cuanto deberia ahorrar?'"),("Plan de ahorro 6 meses","'Crea un plan de ahorro 6 meses para ahorrar [cantidad]. De donde sacar el dinero y como mantenerme motivado.'"),("Regla 50/30/20","'Aplica 50/30/20 a mis finanzas. Analiza mis gastos actuales: cumplo la regla? Que ajustes hacer?'")]},
    {"kw":"analizar inversiones con chatgpt","target":"analizar inversiones con ChatGPT","title":"Analiza tus inversiones con ChatGPT","desc":"Usa IA para analizar carteras, evaluar riesgos y tomar decisiones financieras informadas.","sections":[("Analisis de cartera","'Analiza mi cartera [composicion]: diversificacion, riesgo, rentabilidad, comisiones. Dime nota, puntos fuertes y debiles.'"),("Comparativa de opciones","'Compara estas opciones: [rentabilidad, riesgo, plazo, liquidez]. Recomiendame la mejor justificando.'"),("Evaluacion de riesgo","'Evalua el riesgo de mi cartera: volatilidad, concentracion, divisa, horizonte. Calificacion 1-10 y como mejorarla.'")]},
    {"kw":"presupuesto familiar con inteligencia artificial","target":"presupuesto familiar con IA","title":"Gestiona el presupuesto familiar con inteligencia artificial","desc":"Controla las finanzas de tu hogar con IA. Presupuestos y ahorro para toda la familia.","sections":[("Presupuesto familiar","'Somos [miembros] con ingresos [X]. Gastos fijos: [lista]. Variables: [lista]. Objetivos: [ahorro, viaje]. Crea presupuesto realista.'"),("Seguimiento mensual","'Compara gastos del mes con presupuesto. Donde nos desviamos? Areas de mejora? Progresamos hacia metas?'"),("Planificacion 5 anos","'Planifica 5 anos: educacion hijos, vacaciones, vivienda, jubilacion. Es factible con ingresos actuales?'")]},
    {"kw":"declaracion renta con chatgpt","target":"declaracion de la renta con ChatGPT","title":"Preparate para la declaracion de la renta con ChatGPT","desc":"Organiza tu documentacion fiscal con IA. Sin errores ni sorpresas.","sections":[("Organiza documentacion","'Ayudame a organizar la documentacion: ingresos, extras, deducciones, gastos. Checklist completo para mi situacion.'"),("Calculo de deducciones","'Identifica deducciones a las que opto segun mi situacion. Calcula cuanto podria ahorrar con cada una.'"),("Simulacion","'Simula mi declaracion: ingresos [X], retenciones [Y], deducciones [Z]. Me sale a pagar o devolver? Cuanto?'")]},
    {"kw":"educacion financiera con ia","target":"educacion financiera con IA","title":"Aprende educacion financiera con inteligencia artificial","desc":"Curso personalizado de finanzas con ChatGPT. Conceptos clave a tu ritmo.","sections":[("Diagnostico de nivel","'Evalua mi nivel: presupuesto, ahorro, inversion, deudas. Segun mis respuestas, crea plan de aprendizaje.'"),("Conceptos explicados","'Explicame [concepto] como si tuviera 12 anos con analogias. Despues dame 3 preguntas para verificar.'"),("Casos practicos","'Dame un caso practico de [tema]. Quiero el caso, pistas y solucion paso a paso.'")]},
    {"kw":"reducir deudas con inteligencia artificial","target":"reducir deudas con IA","title":"Reduce tus deudas con un plan creado por IA","desc":"Estrategias personalizadas para salir de deudas. Metodo bola de nieve o avalancha.","sections":[("Diagnostico","'Tengo estas deudas: [cantidad, interes, pago minimo]. Es manejable? Que metodo recomiendas? En cuanto tiempo libre?'"),("Plan de pago","'Crea plan mes a mes con [X]€ disponibles. Usa metodo [bola nieve/avalancha]. Calendario y fecha estimada.'"),("Negociacion","'Preparame para negociar mi deuda con [entidad]. Guion: que decir, ofrecer, aceptar y rechazar.'")]},
    {"kw":"crear fondo emergencia con ia","target":"crear fondo emergencia con IA","title":"Crea tu fondo de emergencia con IA","desc":"Planifica y construye tu fondo de emergencia. Calcula cuanto necesitas.","sections":[("Calcula tu fondo","'Gastos mensuales esenciales: [X]. Meses cobertura: 3-6. Ingresos: [estables/variables]. Dime la cifra exacta.'"),("Plan de ahorro","'Plan para ahorrar [cantidad] en [plazo] meses. Tabla de ahorro mensual y pequenas victorias.'"),("Donde guardarlo","'Donde guardar [cantidad]? Compara: cuenta ahorro, deposito, fondo monetario. Liquidez, riesgo y algo de interes.'")]},
    {"kw":"gastos hormiga detectar ia","target":"detectar gastos hormiga con IA","title":"Detecta gastos hormiga con inteligencia artificial","desc":"Pequenos gastos que suman cientos de euros al ano. Descubrelos con IA.","sections":[("Caza de gastos","'Revisa mis gastos 3 meses: gastos <5€ recurrentes, suscripciones que no uso, compras impulsivas. Total acumulado.'"),("Impacto anual","'Calcula el impacto anual de estos gastos. Si se invirtiera al 7% en 10 anos, cuanto seria?'"),("Plan 30 dias","'Plan de 30 dias: cada semana identificar 3 gastos, estrategia para eliminarlos, recompensa.'")]},
    {"kw":"planificar jubilacion con ia","target":"planificar jubilacion con IA","title":"Planifica tu jubilacion con inteligencia artificial","desc":"Calcula cuanto necesitas para jubilarte. Plan personalizado con IA.","sections":[("Calcula tu numero","'Quiero jubilarme a [edad]. Gasto mensual: [X]. Esperanza vida: [Y]. Inflacion 2.5%. Cuanto necesito?'"),("Estrategia","'Llego a mi objetivo con ahorro de [X]/mes? Varios escenarios segun edad.'"),("Optimizacion fiscal","'Que vehiculos recomiendas: plan pensiones, PPAS, index funds, inmobiliario? Compara ventajas.'")]},
    {"kw":"controlar suscripciones con ia","target":"controlar suscripciones con IA","title":"Controla tus suscripciones con inteligencia artificial","desc":"Cuanto pagas al mes en suscripciones que ni usas? Ahorra cientos de euros.","sections":[("Auditoria","'Revisa mis suscripciones [lista]: esenciales, prescindibles, no usadas. Total mensual y anual.'"),("Plan cancelacion","'Que cancelar hoy, que reducir, que compartir, que revisar en 3 meses.'"),("Alternativas","'Para cada suscripcion, hay alternativas mas baratas o gratuitas? Compara funciones.')]},
    {"kw":"ingresos extra con inteligencia artificial","target":"ingresos extra con IA","title":"Genera ingresos extra con inteligencia artificial","desc":"Gana dinero adicional usando IA. Ideas y automatizacion.","sections":[("Ideas","'Tengo [habilidades] y [X]h/semana. Dame 5 ideas concretas con IA para empezar esta semana.'"),("Automatiza tu side hustle","'Automatiza [idea] con IA. Procesos automatizables, herramientas, flujo completo.'"),("Escala","'En 3 meses genero [X]€/mes. Ayudame a escalar: que funciona, que delegar, como duplicar.'")]},
]

MARKETING = [
    {"kw":"crear contenido redes sociales con chatgpt","target":"crear contenido redes sociales con ChatGPT","title":"Crea contenido para redes sociales con ChatGPT","desc":"Genera posts y contenido para todas tus redes con IA. Ahorra horas de creacion.","sections":[("Calendario mensual","'Crea calendario de contenido para [mes] en [red]. Nicho: [tema]. 20 ideas con titulo, formato, copy y CTA.'"),("Adapta a cada red","'Adapta este contenido [texto] a: Instagram, LinkedIn, Twitter, TikTok. Cada version natural en su plataforma.'"),("Optimiza engagement","'Analiza mis posts buenos [datos] y malos [datos]. Patrones: titulos, longitud, tono, horario. Dame plantilla optimizada.'")]},
    {"kw":"copywriting persuasivo con ia","target":"copywriting persuasivo con IA","title":"Copywriting persuasivo con inteligencia artificial","desc":"Escribe textos que venden usando prompts de IA. Tecnicas profesionales.","sections":[("Estructura AIDA","'Escribe copy AIDA para [producto]. Publico: [target]. Dolor: [problema]. Cada seccion 2-3 lineas.'"),("Prueba social","'5 versiones de prueba social: testimonial, estadistica, autoridad, escasez, comunidad.'"),("CTAs que convierten","'10 CTAs para [pagina]: urgencia, curiosidad, valor, seguridad, exclusion.'")]},
    {"kw":"email marketing automatizado con ia","target":"email marketing automatizado con IA","title":"Email marketing automatizado con IA","desc":"Crea secuencias de email que convierten. Campanas automatizadas con prompts.","sections":[("Bienvenida","'3 emails de bienvenida: Lead magnet [recurso]. Objetivo: confianza y primera compra. Tono cercano.'"),("Email de ventas","'Email de ventas para [producto] a [X]€. Estructura: problema, solucion, prueba social, CTA. Max 150 palabras.'"),("Recuperacion carrito","'3 emails para carritos abandonados: recordatorio (dia 1), valor (3), ultima oportunidad (5).'")]},
    {"kw":"posicionamiento seo con ia","target":"posicionamiento SEO con IA","title":"Posiciona tu web en Google con IA","desc":"Estrategias SEO potenciadas con IA. Keywords, on-page y analisis de competencia.","sections":[("Keyword research","'20 keywords principales, 50 long-tail, preguntas frecuentes, keywords de competidores. En espanol.'"),("Optimizacion on-page","'Analiza [URL]: title, description, H1/H2, keywords, enlaces internos. Plan ordenado por impacto.'"),("Content clusters","'Estrategia de clusters: tema principal, 10 subtemas, enlaces entre ellos, keywords objetivo.'")]},
    {"kw":"estrategia marketing digital con gemini","target":"estrategia marketing digital con Gemini","title":"Estrategia de marketing digital con Google Gemini","desc":"Disena tu estrategia de marketing con Gemini integrado con Google.","sections":[("Auditoria","'Analiza mi marketing con Google Analytics: mejores canales, embudo, cuellos de botella, oportunidades.'"),("Estrategia 3 meses","'Estrategia multicanal 3 meses: SEO, email, redes, contenido. Presupuesto [X]. Objetivo [ventas]. KPIs.'"),("Optimizacion","'Analiza mi ultima campana [datos]. Que funciono, que no, 3 cambios para la proxima.'")]},
    {"kw":"analisis competencia con ia","target":"analisis competencia con IA","title":"Analiza a tu competencia con IA","desc":"Descubre que hace tu competencia y como superarlos.","sections":[("Perfil competidores","'Analiza [competidores]: propuesta valor, publico, canales, fortalezas, debilidades. Huecos de mercado.'"),("Analisis contenido","'Compara mi contenido [URL] con competidor [URL]. Profundidad, calidad, keywords, freshness.'"),("Diferenciacion","'Mi ventaja competitiva unica? 3 areas para diferenciarme y mensajes clave.'")]},
    {"kw":"publicidad google ads con ia","target":"anuncios Google Ads con IA","title":"Crea campanas de Google Ads con IA","desc":"Anuncios que convierten. Keywords y copy optimizados por IA.","sections":[("Estructura","'Disena estructura de campana para [producto]. Presupuesto [X]/dia. Grupos, keywords y pujas.'"),("Anuncios","'5 anuncios de texto. Titulos 30/30 chars, descripcion 90 chars. Maximiza CTR.'"),("Optimiza","'Analiza mi campana [metricas]. 5 optimizaciones concretas ordenadas por impacto.'")]},
    {"kw":"plan marketing contenido con ia","target":"plan marketing contenido con IA","title":"Plan de marketing de contenidos con IA","desc":"Planifica tu estrategia de contenidos. Temas, formatos y calendario.","sections":[("Estrategia","'Estrategia de contenidos para [nicho]. Pilares, temas y formato recomendado.'"),("Calendario editorial","'Calendario 3 meses. Frecuencia [X]/semana. Titulo, keywords, formato, CTA por articulo.'"),("Repurposing","'Transforma mi contenido existente: articulo a hilo, video a blog, podcast a infografia.'")]},
    {"kw":"ventas con chatgpt prompts","target":"ventas con ChatGPT","title":"Cierra mas ventas usando ChatGPT","desc":"Mejora tu proceso de ventas con IA. Scripts, objeciones y seguimiento.","sections":[("Script llamada","'Script de llamada para [producto]. Perfil [target]. Apertura, descubrimiento, objeciones, cierre.'"),("Objeciones","'Responde 5 objeciones comunes en [sector]. 3 enfoques cada una: empatia, logica, prueba social.'"),("Seguimiento","'Secuencia 30 dias post-venta: retencion, upselling, referidos.'")]},
    {"kw":"personalizar mensajes marketing con ia","target":"personalizar marketing con IA","title":"Personaliza mensajes de marketing con IA","desc":"Comunicaciones personalizadas para cada segmento. Marketing uno a uno.","sections":[("Segmentacion","'Segmenta mi audiencia en 4-5 grupos con: caracteristicas, necesidades, tono recomendado.'"),("Mensajes por segmento","'Email promocional para cada segmento de [producto]. Tono y enfoque diferentes.'"),("Pruebas A/B","'3 variantes de este mensaje: cambiar titular, CTA o prueba social. Explica que prueba cada una.'")]},
    {"kw":"analytics interpretar datos con ia","target":"interpretar analytics con IA","title":"Interpreta datos de analytics con IA","desc":"Convierte datos en decisiones. Con ChatGPT.","sections":[("Informe","'Analiza Google Analytics del mes: tendencias, mejores paginas, fuentes de trafico, 3 recomendaciones.'"),("Comportamiento","'Patrones de navegacion, paginas de salida, oportunidades de optimizacion del embudo.'"),("Dashboard","'Propuesta de KPIs: adquisicion, comportamiento, conversion y retencion con formulas y benchmarks.'")]},
    {"kw":"branding personal con ia","target":"branding personal con IA","title":"Construye tu marca personal con IA","desc":"Define y comunica tu marca personal. Posicionate como referente.","sections":[("Define tu marca","'Mi experiencia [background]. Publico [target]. Diferenciacion [unico]. Dame propuesta de valor y 3 pilares.'"),("Plan 30 dias","'15 ideas de posts para [LinkedIn/Twitter] sobre [sector]. Con estructura.'"),("Biografia","'3 versiones: LinkedIn (300pal), Web (100pal), Redes (2 lineas). Tono coherente.'")]},
]

ESTUDIANTES = [
    {"kw":"tomar apuntes con chatgpt","target":"tomar apuntes con ChatGPT","title":"Toma apuntes perfectos con ChatGPT","desc":"Mejora tus apuntes con IA. Mas claros, organizados y utiles.","sections":[("Apuntes estructurados","'Reorganiza estos apuntes: ideas principales, conceptos clave, ejemplos, preguntas de repaso.'"),("Mapas mentales","'Convierte apuntes en mapa mental: tema central, 3-5 ramas, subramas con detalles.'"),("Conexiones","'Identifica conexiones entre [tema A] y [tema B]. Conceptos transversales y principios comunes.'")]},
    {"kw":"resumir libros para estudiar con ia","target":"resumir libros con IA","title":"Resume libros academicos con IA","desc":"Ahorra horas de lectura. Resumenes que mantienen conceptos clave.","sections":[("Por capitulos","'Resume capitulo [X]: tesis, 3 argumentos, ejemplos, terminos nuevos.'"),("Fichas estudio","'Crea 10 fichas: concepto-definicion. Formato pregunta-respuesta.'"),("Contrasta autores","'Compara [autor A] vs [autor B] sobre [tema]. Acuerdos, desacuerdos, sintesis.'")]},
    {"kw":"preparar examenes con inteligencia artificial","target":"preparar examenes con IA","title":"Prepara examenes con inteligencia artificial","desc":"Maximiza rendimiento en examenes. Simulacros y repaso optimizado.","sections":[("Simulacro","'20 preguntas tipo test de [materia]. 4 opciones, respuesta correcta y explicacion.'"),("Desarrollo","'5 preguntas de desarrollo con criterios de evaluacion y respuesta modelo.'"),("Plan repaso","'Plan de repaso diario para [materia] hasta [fecha]. Prioriza mis temas debiles.'")]},
    {"kw":"hacer trabajos academicos con chatgpt","target":"trabajos academicos con ChatGPT","title":"Haz trabajos academicos con ChatGPT (bien usado)","desc":"ChatGPT como apoyo para tus trabajos. Investigacion y estructura etica.","sections":[("Estructura","'Indice detallado para trabajo sobre [tema]. Secciones y frase clave de cada una.'"),("Investigacion","'Fuentes academicas: lineas de investigacion, autores clave, debates actuales.'"),("Revision","'Revisa este parrafo [texto]: claridad, rigor, fluidez. No reescribas, solo sugiere.'")]},
    {"kw":"organizar horario estudio con ia","target":"organizar horario estudio con IA","title":"Organiza tu horario de estudio con IA","desc":"Horarios optimizados con ayuda de IA. Maximo rendimiento academico.","sections":[("Horario semanal","'Horario con [asignaturas], [X]h/dia, prefiero [manana/tarde]. Descansos cada 90 min.'"),("Priorizacion","'Distribuye [X]h entre mis asignaturas: urgencia, dificultad e importancia.'"),("Tecnicas","'Incorpora Pomodoro, repaso espaciado, practica activa. Horario detallado.'")]},
    {"kw":"aprender idiomas con chatgpt","target":"aprender idiomas con ChatGPT","title":"Aprende idiomas mas rapido con ChatGPT","desc":"Tutor personal de idiomas. Practica de conversacion y vocabulario.","sections":[("Conversacion","'Actua como nativo de [idioma] nivel [basico/medio]. Conversacion sobre [tema]. Corrigeme.'"),("Correccion","'Revisa mi texto [texto]: errores, vocabulario, expresiones. Explica cada correccion.'"),("Vocabulario","'20 palabras de [tema] en [idioma] con traduccion, 5 frases, dialogo de ejemplo.'")]},
    {"kw":"tesina trabajo fin grado con ia","target":"TFG/Tesina con IA","title":"Completa tu TFG con ayuda de IA","desc":"Guia etica para tu Trabajo de Fin de Grado con IA.","sections":[("Define el tema","'5 ideas de TFG en [area]: pregunta, objetivos, metodologia, fuentes.'"),("Marco teorico","'Estructura del marco teorico: conceptos, teorias, autores, debates. Esquema completo.'"),("Metodologia","'Metodologia recomendada para [tema]. Compara cuanti/cuali/mixta.'")]},
    {"kw":"matematicas con inteligencia artificial","target":"matematicas con IA","title":"Resuelve problemas de matematicas con IA","desc":"Entiende y resuelve problemas. De algebra a calculo.","sections":[("Paso a paso","'Resuelve [problema] paso a paso. Explica conceptos, justificacion y ejercicio similar.'"),("Conceptos","'Explica [concepto] de 3 formas: formula, ejemplo visual, analogia real.'"),("Practica","'5 problemas de [tema] nivel [basico/medio]. Resuelvo y tu me corriges.'")]},
    {"kw":"leer articulos cientificos con ia","target":"leer articulos cientificos con IA","title":"Lee articulos cientificos con IA","desc":"Comprende papers complejos. Extrae lo esencial sin perder rigor.","sections":[("Resumen","'Resume paper: pregunta, metodologia, resultados, limitaciones, contribucion. Max 300pal.'"),("Glosario","'Terminos tecnicos del paper explicados en lenguaje sencillo con contexto.'"),("Conexion","'Como se relaciona este paper con [otros]? Confirma, contradice o complementa?'")]},
    {"kw":"citar fuentes academicas con ia","target":"citar fuentes con IA","title":"Cita fuentes correctamente con ChatGPT","desc":"Genera citas y referencias en APA, MLA, Chicago y mas.","sections":[("Generacion","'Cita en APA 7ª: [titulo, autor, ano, editorial]. Cita en texto y referencia completa.'"),("Bibliografia","'Bibliografia en [formato] a partir de estas fuentes. Orden alfabetico.'"),("Verificacion","'Revisa estas citas: formato correcto? Elementos presentes? Ortografia correcta?'")]},
    {"kw":"presentaciones academicas con ia","target":"presentaciones academicas con IA","title":"Crea presentaciones academicas con IA","desc":"Diapositivas claras y efectivas para la universidad.","sections":[("Estructura","'Presentacion [X]min sobre [tema]. Diapositivas con contenido y tiempo.'"),("Por diapositiva","'Titulo, 3 viinetas, notas del presentador. Visual, no texto.'"),("Defensa","'10 posibles preguntas para mi defensa con respuestas preparadas.'")]},
    {"kw":"motivacion estudio con ia","target":"motivacion estudio con IA","title":"Mantiene la motivacion para estudiar con IA","desc":"Supera la procrastinacion. Coach academico con IA.","sections":[("Supera bloqueo","'Llevo [X] dias sin estudiar. Mi bloqueo: [describir]. 1 micro-objetivo para hoy y estrategia.'"),("Rutina 30 dias","'Rutina 30 dias para crear habito de [X]h/dia. Encadena con algo que ya hago.'"),("Celebra","'Llevo [X] dias cumpliendo. Reconocimiento y plan para la proxima semana motivado.'")]},
]

RRHH = [
    {"kw":"seleccionar candidatos con inteligencia artificial","target":"seleccionar candidatos con IA","title":"Selecciona candidatos mas rapido con IA","desc":"Automatiza la criba de CVs y evaluacion con ayuda de IA.","sections":[("Criba CVs","'Revisa 10 CVs para [puesto]. Criterios [obligatorios], [deseables]. Clasifica: entrevista si, quiza, descarte.'"),("Preguntas entrevista","'15 preguntas para [puesto]: tecnicas, blandas, motivacion, casos practicos.'"),("Evaluacion final","'Compara 3 finalistas: experiencia, habilidades, salario, cultural fit. Recomendacion.'")]},
    {"kw":"evaluar desempeno empleados con chatgpt","target":"evaluar desempeno con ChatGPT","title":"Evalua el desempeno de tus empleados con ChatGPT","desc":"Evaluaciones objetivas y constructivas con ayuda de IA.","sections":[("Plantilla","'Plantilla evaluacion para [puesto]: resultados, competencias, valores. Escala 1-5.'"),("Feedback","'Feedback a [empleado] sobre [situacion]. 3 enfoques: directo, constructivo, concreto.'"),("Plan mejora","'Plan 30 dias para bajo rendimiento en [areas]. Objetivos semanales y criterios de exito.'")]},
    {"kw":"descripcion puestos trabajo con ia","target":"descripciones de puestos con IA","title":"Crea descripciones de puestos con IA","desc":"Descripciones de empleo atractivas en minutos. Mejores candidatos.","sections":[("Completa","'Descripcion de [puesto] para [industria]: resumen, responsabilidades, requisitos, beneficios.'"),("Optimizada","'Reescribe para maximizar candidaturas de calidad. Clara, atractiva, inclusiva.'"),("Requisitos","'Clasifica requisitos en: imprescindibles, importantes, nice-to-have. No pedir sobrecualificados.'")]},
    {"kw":"onboarding nuevos empleados con ia","target":"onboarding empleados con IA","title":"Automatiza el onboarding con IA","desc":"Incorporacion perfecta. Empleados productivos desde el dia 1.","sections":[("Plan 30 dias","'Plan onboarding para [puesto]: dia1, semana1, mes1. Hitos y responsables.'"),("Guia bienvenida","'Guia para nuevos empleados: historia, cultura, organigrama, politicas, FAQs.'"),("Checklist","'Checklist detallado: antes del dia1, dia1, semana1, mes1. IT, RH, equipo, manager.'")]},
    {"kw":"clima laboral encuestas con ia","target":"clima laboral con IA","title":"Evalua el clima laboral con encuestas inteligentes","desc":"Crea y analiza encuestas de clima. Mejora la satisfaccion.","sections":[("Diseno","'15 preguntas: satisfaccion, jefe, companeros, condiciones, crecimiento. Cuanti + cuali.'"),("Analisis","'Analiza respuestas: puntuacion global, mejores/peores, patrones, areas criticas.'"),("Plan accion","'Plan 3 meses para las 3 peores areas. Objetivo, acciones, responsable, revision.'")]},
    {"kw":"formacion empleados con inteligencia artificial","target":"formacion empleados con IA","title":"Planes de formacion con IA","desc":"Programas de capacitacion personalizados. Desarrolla tu equipo.","sections":[("Necesidades","'Habilidades necesarias 6 meses, brechas actuales, prioridades ordenadas por impacto.'"),("Plan 3 meses","'Programa para [equipo]. Objetivos, formato, presupuesto, temas y evaluacion.'"),("ROI","'Sistema de evaluacion: previa, posterior, seguimiento 30 dias, metricas de aplicacion.'")]},
    {"kw":"entrevistas trabajo con chatgpt","target":"entrevistas de trabajo con ChatGPT","title":"Prepara entrevistas de trabajo con ChatGPT","desc":"Como entrevistador o candidato. Preparacion efectiva.","sections":[("Para candidato","'Preparame para [puesto] en [empresa]: preguntas, metodo STAR, puntos fuertes.'"),("Simulacion","'Entrevistame 20 min para [puesto]. Despues dame feedback y nota.'"),("Post-entrevista","'Evalua al candidato: cumple requisitos? Cultural fit? Alertas? Siguiente paso?'")]},
    {"kw":"gestion talento con inteligencia artificial","target":"gestion talento con IA","title":"Gestion del talento con IA","desc":"Identifica, desarrolla y reten talento. People analytics.","sections":[("Identificacion","'Analiza mi equipo: alto potencial, listos para promocion, riesgo fuga, brechas.'"),("Plan carrera","'Plan 12 meses para [empleado]: habilidades, proyectos, mentor, hitos.'"),("Retencion","'Factores de retencion segun datos. Plan para roles criticos.'")]},
    {"kw":"nominas contratos con ia","target":"nominas y contratos con IA","title":"Gestiona nominas y contratos con IA","desc":"Redaccion de contratos y calculo de nominas automatizado.","sections":[("Contratos","'Contrato para [puesto] [indefinido/temporal]. Condiciones, clausulas legales.'"),("Nominas","'Calcula nomina: salario [X], complementos, IRPF, SS, neto.'"),("Documentacion","'Plantilla para [finiquito/nomina/certificado]. Campos legales.'")]},
    {"kw":"rrhh automatizacion procesos con ia","target":"automatizar RRHH con IA","title":"Automatiza procesos de RRHH con IA","desc":"Identifica y automatiza tareas repetitivas de RRHH.","sections":[("Mapeo","'Analiza procesos RRHH: automatizables, semi-automatizables, humanos. Prioriza por impacto.'"),("Chatbot RH","'Disena chatbot: 20 FAQs con respuestas y flujo de conversacion.'"),("Workflow","'Flujo de aprobaciones: vacaciones, permisos, formacion, gastos. Niveles y escalado.'")]},
    {"kw":"diversidad inclusion empresa con ia","target":"diversidad e inclusion con IA","title":"Fomenta diversidad e inclusion con IA","desc":"Procesos de RH mas inclusivos. Elimina sesgos.","sections":[("Analisis sesgos","'Revisa descripciones de puesto: lenguaje sesgado, requisitos excluyentes, mejoras.'"),("Politica","'Politica de diversidad: compromiso, enfoques, acciones, metricas.'"),("Seleccion inclusiva","'Proceso sin sesgos: CVs ciegos, entrevistas estructuradas, panel diverso.'")]},
    {"kw":"medir productividad equipo con ia","target":"medir productividad con IA","title":"Mide la productividad de tu equipo con IA","desc":"KPIs, dashboard y mejora de rendimiento.","sections":[("KPIs","'5 KPIs para [equipo/rol] con formula, frecuencia y benchmark inicial.'"),("Dashboard","'Dashboard 1 pantalla: metricas individuales, colectivas, tendencias, alertas.'"),("Analisis","'Analiza rendimiento del equipo: mejores, necesitan apoyo, patrones, recomendaciones.'")]},
]

print(f"Datos cargados: Productividad={len(PRODUCTIVIDAD)}, Finanzas={len(FINANZAS)}, Marketing={len(MARKETING)}, Estudiantes={len(ESTUDIANTES)}, RRHH={len(RRHH)}")
